ingestion:
  mode: csv   # options: csv, imap
  csv:
    path: data/sample_emails.csv

send:
  mode: dry_run  # options: dry_run, smtp
  smtp:
    host: smtp.gmail.com
    port: 587
    username: your_email@example.com
    password: your_app_password

llm:
  provider: local  # options: local, openai
  openai:
    model: gpt-4o-mini
    api_key_env: OPENAI_API_KEY
